"""Safe output-directory lifecycle and static asset copying."""

from contextlib import contextmanager
from pathlib import Path
import shutil
import tempfile
from typing import Any

from .errors import ZenFolioBuildError


class OutputManager:
    """Validate, replace, and populate one generated-site directory."""

    def __init__(
        self,
        config: Any,
        content_dir: Path,
        static_dir: Path,
        output_dir: Path,
    ):
        self.config = config
        self.content_dir = content_dir
        self.static_dir = static_dir
        self.output_dir = output_dir

    def validate(self) -> None:
        output = self.output_dir.resolve()
        content = self.content_dir.resolve()
        static = self.static_dir.resolve()
        root = Path(output.anchor).resolve()
        home = Path.home().resolve()

        if output in {root, home, content, static}:
            raise ZenFolioBuildError(
                f"Refusing unsafe output directory: {output}"
            )
        if content.is_relative_to(output):
            raise ZenFolioBuildError(
                "Output directory cannot contain the content directory"
            )
        if output.is_relative_to(static) or static.is_relative_to(output):
            raise ZenFolioBuildError(
                "Output directory cannot overlap the static directory"
            )
        if not output.exists():
            return
        if not output.is_dir():
            raise ZenFolioBuildError(
                f"Output path is not a directory: {output}"
            )

        marker = output / ".zenfolio-build"
        configured_output = Path(self.config.output_path).expanduser()
        if not configured_output.is_absolute():
            configured_output = self.content_dir / configured_output
        configured_output = configured_output.resolve()
        is_empty = not any(output.iterdir())
        # A pre-marker ZenFolio build is recognized by its generated theme
        # assets, not just index.html + sitemap.xml — a hand-written or
        # Jekyll site routinely has those two and must never be deleted.
        theme_assets = (
            output / "static" / "theme.css",
            output / "static" / "style.css",
        )
        is_legacy_build = (
            output == configured_output
            and (output / "index.html").is_file()
            and (output / "sitemap.xml").is_file()
            and any(asset.is_file() for asset in theme_assets)
        )
        if not marker.is_file() and not is_empty and not is_legacy_build:
            raise ZenFolioBuildError(
                "Refusing to delete an existing directory that is not "
                "marked as ZenFolio output. Choose an empty path or remove "
                "the directory explicitly."
            )

    def reset(self) -> None:
        self.validate()
        if self.output_dir.exists():
            shutil.rmtree(self.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        (self.output_dir / ".zenfolio-build").write_text(
            "Generated by ZenFolio. Safe to replace.\n",
            encoding="utf-8",
        )

    @contextmanager
    def staging(self):
        """Generate beside the destination, publishing only a complete build.

        Keeping staging and backup directories on the same filesystem permits
        rename-based publication. An unsuccessful replacement restores the
        previous build before the error is propagated.
        """
        self.validate()
        self.output_dir.parent.mkdir(parents=True, exist_ok=True)
        staging_dir = Path(tempfile.mkdtemp(
            prefix=f".{self.output_dir.name}.zenfolio-stage-",
            dir=str(self.output_dir.parent),
        ))
        staged = OutputManager(
            self.config, self.content_dir, self.static_dir, staging_dir
        )
        try:
            yield staged
            self.publish(staging_dir)
        finally:
            if staging_dir.exists():
                shutil.rmtree(staging_dir)

    def publish(self, staging_dir: Path) -> None:
        """Replace a validated destination, retaining a rollback copy."""
        self.validate()
        backup = None
        if self.output_dir.exists():
            backup = Path(tempfile.mkdtemp(
                prefix=f".{self.output_dir.name}.zenfolio-backup-",
                dir=str(self.output_dir.parent),
            ))
            backup.rmdir()
            self.output_dir.replace(backup)
        try:
            staging_dir.replace(self.output_dir)
        except BaseException as error:
            if backup is not None:
                try:
                    backup.replace(self.output_dir)
                except OSError as rollback_error:
                    raise ZenFolioBuildError(
                        f"Could not publish the build or restore its output. "
                        f"The previous site is preserved at {backup}: "
                        f"{rollback_error}"
                    ) from error
            raise
        if backup is not None:
            try:
                shutil.rmtree(backup)
            except OSError as error:
                # Publication succeeded; a leftover backup is recoverable and
                # must not turn a successful replacement into a failed build.
                print(f"⚠️ Could not remove previous build at {backup}: {error}")

    def copy_static_files(self) -> None:
        if not self.static_dir.exists():
            return
        target = self.output_dir / "static"
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(self.static_dir, target)

    def prepare(self, theme: Any) -> None:
        self.reset()
        print("📋 Copying static files...")
        self.copy_static_files()
        print("🎨 Writing theme assets...")
        theme.write_css_file(self.output_dir)
        theme.write_js_file(self.output_dir)

        robots_source = self.static_dir / "robots.txt"
        if robots_source.exists():
            shutil.copy2(robots_source, self.output_dir / "robots.txt")
