"""Safe output-directory lifecycle and static asset copying."""

from pathlib import Path
import shutil
from typing import Any

from .errors import ZenFolioBuildError


def is_relative_to(path: Path, parent: Path) -> bool:
    """Python 3.8-compatible Path.is_relative_to()."""

    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


class OutputManager:
    """Validate, replace, and populate one generated-site directory."""

    def __init__(
        self,
        config: Any,
        content_dir: Path,
        static_dir: Path,
        output_dir: Path,
    ):
        self.config = config
        self.content_dir = content_dir
        self.static_dir = static_dir
        self.output_dir = output_dir

    def validate(self) -> None:
        output = self.output_dir.resolve()
        content = self.content_dir.resolve()
        static = self.static_dir.resolve()
        root = Path(output.anchor).resolve()
        home = Path.home().resolve()

        if output in {root, home, content, static}:
            raise ZenFolioBuildError(
                f"Refusing unsafe output directory: {output}"
            )
        if is_relative_to(content, output):
            raise ZenFolioBuildError(
                "Output directory cannot contain the content directory"
            )
        if is_relative_to(output, static) or is_relative_to(static, output):
            raise ZenFolioBuildError(
                "Output directory cannot overlap the static directory"
            )
        if not output.exists():
            return
        if not output.is_dir():
            raise ZenFolioBuildError(
                f"Output path is not a directory: {output}"
            )

        marker = output / ".zenfolio-build"
        configured_output = Path(self.config.output_path).expanduser()
        if not configured_output.is_absolute():
            configured_output = self.content_dir / configured_output
        configured_output = configured_output.resolve()
        is_empty = not any(output.iterdir())
        is_legacy_build = (
            output == configured_output
            and (output / "index.html").is_file()
            and (output / "sitemap.xml").is_file()
        )
        if not marker.is_file() and not is_empty and not is_legacy_build:
            raise ZenFolioBuildError(
                "Refusing to delete an existing directory that is not "
                "marked as ZenFolio output. Choose an empty path or remove "
                "the directory explicitly."
            )

    def reset(self) -> None:
        self.validate()
        if self.output_dir.exists():
            shutil.rmtree(self.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        (self.output_dir / ".zenfolio-build").write_text(
            "Generated by ZenFolio. Safe to replace.\n",
            encoding="utf-8",
        )

    def copy_static_files(self) -> None:
        if not self.static_dir.exists():
            return
        target = self.output_dir / "static"
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(self.static_dir, target)

    def prepare(self, theme: Any) -> None:
        self.reset()
        print("📋 Copying static files...")
        self.copy_static_files()
        print("🎨 Writing theme assets...")
        theme.write_css_file(self.output_dir)
        theme.write_js_file(self.output_dir)

        robots_source = self.static_dir / "robots.txt"
        if robots_source.exists():
            shutil.copy2(robots_source, self.output_dir / "robots.txt")
